"use client";
import React, { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { counterReducer } from '@/store/Reducers/controlreducers';
import { asyncGetStudent } from '@/store/Action/action';
import { ToastContainer, toast } from 'react-toastify';
import { injectStyle } from "react-toastify/dist/inject-style";
import { configDotenv } from "dotenv"
// export const metadata = {
//   title: 'Login Page',
//   // description: 'Generated by create next app',
// }
const page = () => {
  const {student} = useSelector((state)=>state.counterReducer);
  const {message} = useSelector((state)=>state.counterReducer);
  const dispatch = useDispatch();


  
  return (
    <div>page

    </div>
  )
}

export default page